.PHONY: deploy diff synth deploy-local diff-local synth-local

# Live endpoints
diff:
	cdk diff

synth:
	cdk synth

deploy:
	cdk deploy

# Localstack endpoints
diff-local:
	cdklocal diff

synth-local:
	cdklocal synth

deploy-local:
	cdklocal deploy
